### PR TITLE
Add support for Giphy, YouTube and Twitter

### PR DESCRIPTION
**Pull request by Glodenox**
This commit converts the giphy links to the gif image so these can be shown as well. I suppose we don't want to start supporting all sorts of random services, but Giphy seems pretty big to me.

This commit may clash slightly with my other pull request that replaces the CSS animation with a JavaScript solution that scrolls the page as there are some whitespace differences. It should be fairly straightforward to merge them though.

### CODE REVIEW

**Comment by Glodenox** [comment]
I now also added support for YouTube. I tried to also retrieve the video title via the YouTube API, but it seems that cross-domain requests aren't working that well and I'd rather not start using `GM_xmlhttpRequest`.
The code can be written much better, but this works for now.

**Comment by Glodenox** [comment]
Also added Twitter now. Should we make it configurable by source so you can enable and disable each source?

**Comment by Glodenox** [comment]
I just merged the changes of the current version into this branch, that should make it easier for you to merge.

**Comment by jack-d-watson** [comment]
Can you increment the version number on this? It would be pushed automatically to people's clients when this pull request is approved. Also does this leave the original youtube link?

**Comment by Glodenox** [comment]
Done. I'm used to just committing changes and letting the script maintainer decide on version numbering, that's why I tend not to adjust the version.

This code leaves the original YouTube link in place in the same way as it remains available for gif images currently: by making it possible to click on the image to follow the link to YouTube. The code adds the image inside the existing anchor tag.

**Pull request merged**
