### PR TITLE
Handle images not loading, slide in new chat messages nicely and formatting fixes

### PR DESCRIPTION
**Pull request by Glodenox**
Hey Paul, I've made some changes to the chat monitor that might interest you:

- Whenever an image doesn't load, it currently result in a blank space. Just by adding the URL as alt text to the image, the image URL gets shown if the image couldn't load.
- I've added a quick animation that makes new chat messages slide in from the top, making it a lot easier to keep reading chat while messages are flowing in
- Currently the odd lines are slightly bigger than the even ones, which looks a bit weird. By having all lines have just one border at the bottom, this is fixed. I also played around with the padding and margin as the background didn't always match the borders.

### CODE REVIEW

**Comment by paul-lrr** [comment]
these seem like great fixes. Have you tested it with the current build? (that incorporates cheetojack's config page)

**Comment by Glodenox** [comment]
I based myself on the latest version of the master branch, so that should be the case. I'm seeing the config button and it all seems to run fine here on Firefox and Chrome. The two other pull requests by mas90 don't seem to clash with these changes either as they change other parts of the CSS file.

**Comment by paul-lrr** [comment]
Cool! don't have a lot of experience with github, but I guess it should be good

**Comment by Glodenox** [comment]
This has only been my second pull request so far for me, so it's all still relatively new for me as well :)

**Pull request merged**
